driver: console
level: trace

#driver: rorate # 切割日志
#level: trace # 日志级别
#file: coredemo.log # 保存日志的文件
## rotate_count: 10 # 最多日志文件个数
## rotate_size: 120000
#rotate_time: "1m"
## max_age: "10d" # 文件保存时间
#date_format: "%Y-%m-%d-%H-%M" # 文件后缀格式